### ISSUE TITLE
icub_with_hands gazebo model joint6(wrist_yaw) position cannot be moved using yarpmotorgui

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-gazebo#35] opened 2016-09-29 09:54 UTC
Hello, 

In the icub_with_hands gazebo model joint6(wrist_yaw) position cannot be moved using yarpmotorgui. The initial position is at one of the joint limit values of 24.57 and cannot be moved towards the other joint limit side. This problem does not exists with icub with no hands model 

Thank you

**Comment by randaz81** [comment] 2016-11-08 15:16
I'm sorry but I cannot reproduce this problem. 
I'm using icub_with_hands model, and I'm trying to move joint 6 (wirst_yaw) on both arms from its initial position. I can easily move it from 25 to -19. Maybe I have not understood correctly, or this issue has been already fixed in the past. Can you check it?

**Comment by randaz81** [comment] 2016-11-10 10:59
The fix robotology/QA#155 should have improved joint effort limits. I think that this problem on the wrist_yaw should not happen anymore...

**Comment by Yeshasvitvs** [comment] 2016-11-10 12:04
@randaz81 ciao marco, 

I just tried it and the problem doesn't exist anymore. Thanks for the fix. I also noticed a lot twitching in the fingers even when I am not moving the fingers. I am not sure if it just on my machine, please let me know

**Comment by randaz81** [comment] 2016-11-10 13:37
Uhm, small inertias may lead to numerical instability, however I haven't spotted this issue in my tests.
Let's close this issue, and discuss this new problem on a separated thread.

**Closed by randaz81** 2016-11-10 13:37 UTC
Labels: Status: Feedback
